recycler_in_fragment
PfcRico/WeatherApp pull request #3
Opened 2021-08-10 13:34 UTC by PfcRico

Request is sent, but app crashes :)

2021-08-12 14:25 UTC, atserkovnaya requested changes

2021-08-12 14:25 UTC, atserkovnaya commented on app/build.gradle
> +
please, remove extra line

2021-08-12 14:25 UTC, atserkovnaya commented on app/src/main/java/com/example/weatherapp/data/network/ApiWeatherService.kt
> +                .addCallAdapterFactory(CoroutineCallAdapterFactory())
I guess this is outdate line

2021-08-12 14:25 UTC, atserkovnaya commented on app/src/main/java/com/example/weatherapp/fragment/CityDetailsFragment.kt
> +
extra lines)

2021-08-12 14:25 UTC, atserkovnaya commented on app/src/main/java/com/example/weatherapp/fragment/CityDetailsFragment.kt
> +        arguments?.getString("cityName")?.let {
Please, move "cityName" to constants and use in other places as constant

2021-08-12 14:28 UTC, Jerika commented on app/build.gradle
> +
Please, remove extra line

2021-08-13 13:12 UTC, Jerika requested changes

2021-08-13 13:12 UTC, Jerika commented on app/src/main/res/values/styles.xml
> +<?xml version="1.0" encoding="utf-8"?>
is this empty file really need?

2021-08-13 13:12 UTC, Jerika commented on app/src/main/res/layout/cities_list_fragment.xml
> +
empty line)

2021-08-13 13:12 UTC, Jerika commented on app/src/main/res/layout/city_view_fragment.xml
> +    card_view:cardBackgroundColor="#FFFF"
please, move to colors.xml

2021-08-13 13:34 UTC, Jerika approved these changes

2021-08-13 13:43 UTC, merged